name: ROS2 (Ubuntu)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Based on example provided at https://github.com/ros-tooling/setup-ros

jobs:
  build_docker: # On Linux, use docker
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ros_distribution:
          - humble
          - iron
          - jazzy

        # Define the Docker image(s) associated with each ROS distribution.
        include:
          # Humble Hawksbill (May 2022 - May 2027)
          - docker_image: ubuntu:jammy
            ros_distribution: humble
            ros_version: 2

          # Iron Irwini (May 2023 - Nov 2024)
          - docker_image: ubuntu:jammy
            ros_distribution: iron
            ros_version: 2

          # Jazzy Jalisco (May 2024 - May 2029)
          - docker_image: ubuntu:noble
            ros_distribution: jazzy
            ros_version: 2

    container:
      image: ${{ matrix.docker_image }}
    steps:
      - name: setup ROS environment
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: ${{ matrix.ros_distribution }}

      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install -y libboost-program-options-dev libusb-1.0-0-dev

      - name: install pip dependencies
          # TODO: would be better to follow https://answers.ros.org/question/370666/how-to-declare-an-external-python-dependency-in-ros2/
          # but this requires some upstream changes

          # colcon still does not seem to properly support venv, so we use a workaround to install
          # a python package globally by disabling the externally managed flag that is default on Ubuntu 24.04
        run: |
          sudo rm -f /usr/lib/python3.12/EXTERNALLY-MANAGED
          pip install rowan

      - uses: actions/checkout@v2
      - name: build and test ROS 2
        uses: ros-tooling/action-ros-ci@v0.3
        with:
          package-name: |
            crazyflie
            crazyflie_examples
            crazyflie_interfaces
            crazyflie_py
            crazyflie_sim
          target-ros2-distro: ${{ matrix.ros_distribution }}
          vcs-repo-file-url: rosinstall